apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-demo
  labels:
    app: tekton-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-demo
  template:
    metadata:
      labels:
        app: tekton-demo
    spec:
      containers:
        - name: tekton-demo
          image: tekton-demo
          ports:
            - containerPort: 18010